name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x 

    - name: Restore dependencies
      working-directory: ./BankingSystem
      run: dotnet restore BankingSystem.sln

    - name: Build
      working-directory: ./BankingSystem
      run: dotnet build BankingSystem.sln --no-restore --configuration Release

    - name: Test
      working-directory: ./BankingSystem
      run: dotnet test BankingSystem.sln --no-build --verbosity normal
