name: CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    # Set up .NET SDK
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Install Angular CLI (optional if you use global)
    - name: Install Angular CLI
      run: npm install -g @angular/cli

    # Install Angular dependencies
    - name: Install Angular dependencies
      working-directory: ./BankingSystem/ClientApp/BankingSystem/bankingsystem.client
      run: npm install

    # Build Angular app
    - name: Build Angular app
      working-directory: ./BankingSystem/ClientApp/BankingSystem/bankingsystem.client
      run: ng build --configuration production


    # Restore .NET dependencies
    - name: Restore .NET dependencies
      working-directory: ./BankingSystem
      run: dotnet restore BankingSystem.sln

    # Build .NET app
    - name: Build .NET app
      working-directory: ./BankingSystem/ClientApp/BankingSystem/BankingSystem.Server
      run: dotnet build BankingSystem.Server.csproj --configuration Release --no-restore

    # Publish .NET app
    - name: Publish .NET app
      working-directory: ./BankingSystem/ClientApp/BankingSystem/BankingSystem.Server
      run: dotnet publish BankingSystem.Server.csproj --configuration Release --output ./publish

      # Copy Angular build to ASP.NET Core wwwroot
    - name: Copy Angular build to ASP.NET Core wwwroot
      run: |
        rm -rf ./BankingSystem/ClientApp/BankingSystem/BankingSystem.Server/wwwroot/*
        cp -r ./BankingSystem/ClientApp/BankingSystem/bankingsystem.client/dist/bankingsystem.client/browser/* ./BankingSystem/ClientApp/BankingSystem/BankingSystem.Server/wwwroot/

    # Upload artifact for deploy step
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-app
        path: ./BankingSystem/ClientApp/BankingSystem/BankingSystem.Server/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: dotnet-app

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EF0F9324B811480A80BE4AD35773F6A2 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_636332CC61B3420598021FA6EE9D80FA }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2A0CE8AA9EC64A0E8E877602DC2F812C }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'bankingapplication'
        slot-name: 'Production'
        package: .
